# Generated by Django 2.1.5 on 2019-02-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=0)),
                ('lat', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
            ],
        ),
    ]
